<div  class="col-md-9 mx-auto">
    <h1>Časté otázky</h1>
    <h5>Zde najdete odpovědi na nejčastější otázky. Pokud ani tak nejste o nic moudřejší, <a href="kontakt">napište nám</a> a my se vám ozveme zpět.</h5></br>
    <div class="row justify-content-left">
        <div class="d-flex justify-content-center col-md-3">
            <img src="obrazky/koule.png" alt="Koule" class="img-fluid" style="width: 200px; height: 200px; margin-bottom: 25px;"/>
        </div>
        <div class="d-flex justify-content-center col-md-9">
            <div id="faq" class="col-12">
                <div class="card mb-2">
                    <div class="card-header">
                        <a class="collapsed btn" data-bs-toggle="collapse" href="#collapseKdo">
                            <h6>Kdo se u vás může pojistit?</h6>
                        </a>
                    </div>
                    <div id="collapseKdo" class="collapse" data-bs-parent="#faq">
                        <div class="card-body">
                            Pojištění poskytujeme všem kouzelným bytostem od těch nejdrobnějších skřítků až po nejmajestátnější draky.
                        </div>
                    </div>
                </div>
                <div class="card mb-2">
                    <div class="card-header">
                        <a class="collapsed btn" data-bs-toggle="collapse" href="#collapseUdalosti">
                            <h6>Jaké rizikové události pokrývají vaše pojištění?</h6>
                        </a>
                    </div>
                    <div id="collapseUdalosti" class="collapse" data-bs-parent="#faq">
                        <div class="card-body">
                            Poskytujeme různé typy pojištění pokrývající všemožné rizikové události, protože neštěstí nechodí nikdy samo. Všechna pojištění si můžete prohlédnout <a href="pojisteni" target="_blank">zde</a>.
                        </div>
                    </div>
                </div>
                <div class="card mb-2">
                    <div class="card-header">
                        <a class="collapsed btn" data-bs-toggle="collapse" href="#collapseProces">
                            <h6>Jaký je proces pojistného nároku?</h6>
                        </a>
                    </div>
                    <div id="collapseProces" class="collapse" data-bs-parent="#faq">
                        <div class="card-body">
                            Proces podání nároku je u nás velmi jednoduchý. Kontaktujte nás a poskytněte podrobnosti o události. Naši odborníci vám pomohou s řešením nároku.
                        </div>
                    </div>
                </div>
                <div class="card mb-2">
                    <div class="card-header">
                        <a class="collapsed btn" data-bs-toggle="collapse" href="#collapseHodnota">
                            <h6>Jak stanovím hodnotu předmětu pro účely pojistky?</h6>
                        </a>
                    </div>
                    <div id="collapseHodnota" class="collapse" data-bs-parent="#faq">
                        <div class="card-body">
                            Pro stanovení hodnoty předmětu školíme speciální odbodníky, kteří vám s odhadem pomohou. Jednoduše nás kontaktujte pomocí palantýru, sovy nebo <a href="kontakt"  target="_blank">kontaktního formuláře</a>.
                        </div>
                    </div>
                </div>
                <div class="card mb-2">
                    <div class="card-header">
                        <a class="collapsed btn" data-bs-toggle="collapse" href="#collapsePlatba">
                            <h6>Jaké jsou možnosti platby pojistného poplatku?</h6>      
                        </a>
                    </div>
                    <div id="collapsePlatba" class="collapse" data-bs-parent="#faq">
                        <div class="card-body">
                            Nabízíme různé možnosti platby včetně jednorázové platby nebo měsíčních splátek v závislosti na typu pojištění. Akceptujeme převody na účet i platby v hotovosti u nás na pobočce.</br>
                            Naše klienty chceme důrazně upozornit, že<strong> leprikónské zlato poznáme</strong>, takže to ani nezkoušejte. 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>