<div  class="col-md-9 mx-auto">
    <h1>Kontaktní formulář</h1>
    <h5>Máte nějaké dotazy nebo zpětnou vazbu? Napište nám!</h5></br>
    <div class="row justify-content-left">
        <div class="d-flex justify-content-center col-md-3">
            <img src="obrazky/hulak.png" alt="Hulák" class="img-fluid" style="width: 200px; height: 200px; margin-bottom: 25px;"/>
        </div>
        <div class="d-flex justify-content-center col-md-6">
            <form method="post" id="emailFormular" class="col-12">
                <div>
                    <h6><label for="email">Vaše emailová adresa</label></h6>
                    <input type="email" name="email" class="form-control" id="email" placeholder="adresa@domena.com" autocomplete="off" required value="<?php
                    if (isset($_POST['email'])) {
                        echo(htmlspecialchars(trim($_POST['email'])));
                    }
                    ?>" />
                </div>
                <div>
                    <h6><label for="rok" class="mt-3">Antispam - zadejte aktuální rok</label></h6>
                    <input type="text" name="rok" class="form-control" id="rokAntispam" required="required"/>
                </div>
                <div>
                    <h6><label for="zprava" class="mt-3">Svěřte nám, co máte na srdci</label></h6>
                    <textarea name="zprava" class="form-control" id="zprava" rows="8" placeholder="Jsme jedno velké ucho :-)" ><?php
                        if (isset($_POST['zprava'])) {
                            echo(htmlspecialchars(trim($_POST['zprava'])));
                        }
                        ?></textarea>
                    <div class="d-flex justify-content-center mt-3">
                        <button type="submit" class="btn tlacitko-info">Odeslat</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>