<div class="container">
    <h1 class="text-center">Profil pojištěnce</h1>
    <div class="row">
        <div class="col-12 col-md-4 col-lg-3">
            <img src="obrazky/oslik1.jpg" alt="profilovy" class="img-fluid" />
        </div>
        <div class="col-12 col-md-8 col-lg-9">
            <h2><?= $jmeno . " " . $prijmeni ?></h2>
            <h6><?= "Datum narození: " . date('d.m.Y', strtotime($datumNarozeni)) . ", " . $vek . " let" ?></h6>
            <div class="row">
                <div class="col-md-6">
                    <h5>Kontaktní informace</h5>
                    <p>Email: <?= $email ?></p>
                    <p>Telefonní číslo: <?= $telefon ?></p>
                </div>
                <div class="col-md-6">
                    <h5>Adresa</h5>
                    <p><?= $adresa ?></p>
                    <p><?= $mesto ?></p>
                    <p><?= $psc ?></p>
                </div>
            </div>
            <?php if ($admin) : ?>
                <div class="row">
                    <div class="col-md-12 my-3">
                        <div class="d-flex justify-content-start">
                            <a class="btn tlacitko-warning me-2" href="editor/<?= $pojistenec['url'] ?>">Editovat</a>
                            <button type="button" class="btn tlacitko-danger" data-bs-toggle="modal" data-bs-target="#odstran">Odstranit</button>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="odstran">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Potvrzení odstranění</h4>
                            </div>
                            <div class="modal-body text-center">
                                Opravdu si přejete odstranit pojištěnce <?= $jmeno . " " . $prijmeni ?>?
                            </div>
                            <div class="modal-footer justify-content-center">
                                <button type="button" class="btn tlacitko-success" data-bs-dismiss="modal" >
                                    Vrátit
                                </button>
                                <button type="button" class="btn tlacitko-danger" data-bs-dismiss="modal" >
                                    <a href="pojistenec/<?= $pojistenec['url'] ?>/odstranit" style="color: white; text-decoration: none;">Odstranit</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
   <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-bs-toggle="tab" href="#pojisteni">Pojištění</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" href="#udalosti">Pojistné události</a>
        </li>
    </ul>
    <div class="tab-content">
        <div id="pojisteni" class="container tab-pane active">
            <?php if ($admin) : ?>
                <div class="d-flex justify-content-center mt-3">
                    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#novePojisteni">Přidat nové pojištění</button>
                </div>
                <div class="modal fade" id="novePojisteni">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Nové pojištění pro pojištěnce <?= $jmeno . " " . $prijmeni ?></h4>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <form method="post" class="needs-validation" novalidate id="novePojisteniFormular">
                                <div class="modal-body">
                                    <div class="container">
                                        <input type="hidden" name="pojistenec_id" value="<?= $pojistenecId ?>" />
                                        <div>
                                            <h6 class="mt-3"><label for="typPojisteni" class="form-label">Typ pojištění</label></h6>
                                            <select class="form-select" id="typPojisteni" name="typ_pojisteni" required>
                                                <option value="Úrazové">Úrazové</option>
                                                <option value="Důchodové">Důchodové</option>
                                                <option value="Nemocenské">Nemocenské</option>
                                                <option value="Cestovní">Cestovní</option>
                                                <option value="Havarijní">Havarijní</option>
                                            </select>
                                        </div>
                                        <div>
                                            <h6 class="mt-3"><label for="predmetPojisteni" class="form-label">Předmět pojištění</label></h6>
                                            <select class="form-select" id="predmetPojisteni" name="predmet_pojisteni" required>
                                                <option value="Pojištěnec"><?= $jmeno . " " . $prijmeni ?></option>
                                                <option value="Příbuzný">Příbuzný klienta</option>
                                                <option value="Vozidlo">Vozidlo</option>
                                                <option value="Nemovitost">Nemovitost</option>
                                            </select>
                                        </div>
                                        <div>
                                            <h6 class="mt-3">Platnost</h6>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label for="od" class="form-label">Od:</label>
                                                    <input type="date" name="od" class="form-control od" id="od" value="<?php echo date('Y-m-d') ?>" min="<?= date('Y-m-d') ?>" max="<?= $maximalniDatum ?>" required/>
                                                    <div class="invalid-feedback od_feedback" id="odFeedback">Zadejte platné datum</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <label for="do" class="form-label">Do:</label>
                                                    <input type="date" name="do" class="form-control do" id="do" min="<?= date('Y-m-d') ?>" max="<?= $maximalniDatum ?>" data-bs-toggle="tooltip" data-html="true" title="Uveďte, pokud je stanoveno datum ukončení"/>
                                                    <div class="invalid-feedback do_feedback" id="doFeedback">Zadejte platné nebo žádné datum</div>
                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                            <h6 class="mt-3"><label for="castka" class="form-label">Platba</label></h6>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <input type="number" name="castka" id="castka" class="form-control" oninput="validovatCastku(this)" placeholder="Částka" min="10" required/>
                                                    <div class="invalid-feedback">Hodnota musí být minimálně 10 korun</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <select class="form-select" name="frekvence_platby" id="frekvencePlatby" required>
                                                        <option value="Jednorázově">Jednorázově</option>
                                                        <option value="Měsíčně">Měsíčně</option>
                                                        <option value="Čtvrtletně">Čtvrtletně</option>
                                                        <option value="Ročně">Ročně</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer justify-content-center">
                                    <button type="submit" class="btn tlacitko-success tlacitkoKontrola" id="tlacitkoPridatPojisteni">Přidat pojištění</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            <?php endif ?>
            <div>
                <?php if ($pojisteniPojistence) : ?>
                    <table class="table table-striped table-bordered table-hover my-3">
                        <thead>
                        <th>Typ pojištění</th>
                        <th>Předmět</th>
                        <th>Platnost</th>
                        <th>Částka</th>
                        <th>Platba</th>
                        <th>Zaplaceno</th>
                        <?php if ($admin) : ?>
                            <th>Úpravy</th>
                        <?php endif ?>
                        </thead>
                        <?php foreach ($pojisteniPojistence as $pojisteniPojistence) : ?>   
                            <tr> 
                                <td><?= $pojisteniPojistence['typ_pojisteni'] ?></td>
                                <td>
                                    <?php if ($pojisteniPojistence['predmet_pojisteni'] === 'Pojištěnec') : ?>
                                        <?= $pojistenec['jmeno'] . " " . $pojistenec['prijmeni'] ?>
                                    <?php else : ?>
                                        <?= $pojisteniPojistence['predmet_pojisteni'] ?>
                                    <?php endif ?>
                                </td>
                                <td>
                                    <?php if ($pojisteniPojistence['do'] === '0000-00-00' || $pojisteniPojistence['do'] === '0' || $pojisteniPojistence['do'] === null) : ?>
                                        <?= date('d.m.Y', strtotime($pojisteniPojistence['od'])) . " - bez ukončení" ?>
                                    <?php endif ?>
                                    <?php if ($pojisteniPojistence['do'] != '0000-00-00' && $pojisteniPojistence['do'] != '0' && $pojisteniPojistence['do'] != null) : ?>
                                        <?= date('d.m.Y', strtotime($pojisteniPojistence['od'])) . " - " . date('d.m.Y', strtotime($pojisteniPojistence['do'])) ?>
                                    <?php endif ?>
                                </td>
                                <td><?= $pojisteniPojistence['castka'] ?></td>
                                <td><?= $pojisteniPojistence['frekvence_platby'] ?></td>
                                <td><?= $pojisteniPojistence['celkem_zaplaceno'] ?></td>
                                <?php if ($admin) : ?>
                                    <td>
                                        <div class="container m-md-1 d-flex">
                                            <?php if ($pojisteniPojistence['frekvence_platby'] === 'Jednorázově') : ?>
                                                <button type="button" class="btn btn-sm tlacitko-warning-neaktivni" data-bs-toggle="tooltip" data-html="true" title="Pojištění s jednorázovou platbou nelze upravovat">
                                                    Editovat
                                                </button>
                                            <?php else : ?>
                                                <button type="button" class="btn btn-sm tlacitko-warning" data-bs-toggle="modal" data-bs-target="#uprav<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                                    Editovat
                                                </button>
                                            <?php endif ?>
                                            <div class="modal" id="uprav<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title">Upravte <?= mb_strtolower($pojisteniPojistence['typ_pojisteni']) ?> pojištění pojištěnce <?= $jmeno . " " . $prijmeni ?></h4>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                                        </div>
                                                        <form method="post" class="needs-validation" novalidate id="editacePojisteniFormular">
                                                            <div class="modal-body">
                                                                <div class="container">
                                                                    <input type="hidden" name="pojisteni_id" id="pojisteniIdEditace" value="<?= $pojisteniPojistence['pojisteni_id'] ?>" />
                                                                    <div>
                                                                        <h6 class="mt-3"><label for="typPojisteniEditace" class="form-label">Typ pojištění</label></h6>
                                                                        <input type="text" class="form-control" id="typPojisteniEditace" name="typ_pojisteni" value="<?= $pojisteniPojistence['typ_pojisteni'] ?>" disabled="disabled"/>
                                                                    </div>
                                                                    <div>
                                                                        <h6 class="mt-3"><label for="predmetPojisteniEditace" class="form-label">Předmět pojištění</label></h6>
                                                                        <?php if ($pojisteniPojistence['predmet_pojisteni'] === 'Pojištěnec') : ?>
                                                                            <input type="text" class="form-control" id="predmetPojisteniEditace" name="predmet_pojisteni" value="<?= $pojistenec['jmeno'] . " " . $pojistenec['prijmeni'] ?>" disabled="disabled"/>
                                                                        <?php else : ?>
                                                                            <input type="text" class="form-control" id="predmetPojisteniEditace" name="predmet_pojisteni" value="<?= $pojisteniPojistence['typ_pojisteni'] ?>" disabled="disabled"/>
                                                                        <?php endif ?>
                                                                    </div>
                                                                    <div>
                                                                        <h6 class="mt-3">Platnost</h6>
                                                                        <div class="row">
                                                                            <div class="col-md-6">
                                                                                <label for="od" class="form-label">Od:</label>
                                                                                <input type="date" name="od" class="form-control od_editace" id="odEditace" value="<?= $pojisteniPojistence['od'] ?>" disabled="disabled"/>
                                                                            </div>
                                                                            <div class="col-md-6">
                                                                                <label for="do" class="form-label">Do:</label>
                                                                                <input type="date" name="do" class="form-control od_editace" id="doEditace" value="<?= $pojisteniPojistence['do'] ?>" min="<?= date('Y-m-d') ?>"  max="<?= $maximalniDatum ?>" data-bs-toggle="tooltip" data-html="true" title="Uveďte, pokud je stanoveno datum ukončení"/>
                                                                                <div class="invalid-feedback do_editace_feedback" id="doEditaceFeedback">Zadejte platné nebo žádné datum</div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div>
                                                                        <h6 class="mt-3"><label for="castkaEditace" class="form-label">Platba</label></h6>
                                                                        <div class="row">
                                                                            <div class="col-md-6">
                                                                                <input type="number" name="castka" class="form-control" id="castkaEditace" oninput="validovatCastku(this)" placeholder="Částka" value="<?= $pojisteniPojistence['castka'] ?>" min="10" required/>
                                                                                <div class="invalid-feedback">Hodnota musí být minimálně 10 korun</div>
                                                                            </div>
                                                                            <div class="col-md-6">
                                                                                <select class="form-select" id="frekvencePlatbyEditace" name="frekvence_platby" required>
                                                                                    <option value="Měsíčně">Měsíčně</option>
                                                                                    <option value="Čtvrtletně">Čtvrtletně</option>
                                                                                    <option value="Ročně">Ročně</option>
                                                                                </select>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer justify-content-center">
                                                                <button type="submit" class="btn tlacitko-success tlacitkoKontrola2" id="tlacitkoUpravitPojisteni"">Upravit pojištění</button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                            <button type="button" class="btn btn-sm tlacitko-danger" data-bs-toggle="modal" data-bs-target="#odstran<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                                Odstranit
                                            </button>
                                            <div class="modal" id="odstran<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title">Potvrzení odstranění</h4>
                                                        </div>
                                                        <div class="modal-body text-center">
                                                            Opravdu si přejete odstranit <?= mb_strtolower($pojisteniPojistence['typ_pojisteni']) ?> pojištění?
                                                        </div>
                                                        <form method="post">
                                                            <input type="hidden" name="pojisteni_id" value="<?= $pojisteniPojistence['pojisteni_id'] ?>" />
                                                            <input type="hidden" name="odstranit" value="odstranit" />
                                                            <div class="modal-footer justify-content-center">
                                                                <button type="button" class="btn tlacitko-success" data-bs-dismiss="modal" >
                                                                    Vrátit
                                                                </button>
                                                                <button type="submit" class="btn tlacitko-danger" data-bs-dismiss="modal" >
                                                                    Odstranit
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                <?php endif ?>
                            </tr>
                        <?php endforeach ?>
                    </table>
                <?php else : ?>
                    <p><?= $jmeno . " " . $prijmeni ?> zatím nemá žádné pojištění.</p>
                <?php endif ?>
            </div>
        </div>
        <div id="udalosti" class="container tab-pane fade"></div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        podminkyPojisteni();
        validaceFormulare();
    });
</script>