<h1>Seznam pojištěnců</h1>
<?php if ($admin) : ?>
    <div class="d-flex justify-content-center">
        <a class="btn tlacitko-success" href="editor">Přidat nového pojištěnce</a>
    </div>
<?php endif ?>
<br/>
<?php if ($pojistenci) : ?>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <th>Jméno a příjmení</th>
        <th>Adresa</th>
        <?php if ($admin) : ?>
            <th class="col-3">Úpravy</th>
        <?php endif ?>
    </thead >
    <?php foreach ($pojistenci as $pojistenec) : ?>

        <tr>
            <td>
                <h4 class="m-md-1"><a href="pojistenec/<?= $pojistenec['url'] ?>"><?= $pojistenec['jmeno'] . " " . $pojistenec['prijmeni'] ?></a></h4>
            </td>
            <td>
                <p class="m-md-1"><?= $pojistenec['adresa'] . ", " . $pojistenec['mesto'] . " " . $pojistenec['psc'] ?></p>
            </td>
            <?php if ($admin) : ?>
                <td>
                    <div class="container m-md-1">
                        <button type="button" class="btn tlacitko-warning">
                            <a href="editor/<?= $pojistenec['url'] ?>" style="color: white; text-decoration: none;">Editovat</a>
                        </button>
                        <button type="button" class="btn tlacitko-danger" data-bs-toggle="modal" data-bs-target="#odstranit<?= $pojistenec['url'] ?>">
                            Odstranit
                        </button>
                    </div>
                    <div class="modal" id="odstranit<?= $pojistenec['url'] ?>">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Potvrzení odstranění</h4>
                                </div>
                                <div class="modal-body text-center">
                                    Opravdu si přejete odstranit pojištěnce <?= $pojistenec['jmeno'] . " " . $pojistenec['prijmeni'] ?>?
                                </div>
                                <div class="modal-footer justify-content-center">
                                    <button type="button" class="btn tlacitko-success" data-bs-dismiss="modal" >
                                        Vrátit
                                    </button>
                                    <button type="button" class="btn tlacitko-danger" data-bs-dismiss="modal" >
                                        <a href="pojistenec/<?= $pojistenec['url'] ?>/odstranit" style="color: white; text-decoration: none;">Odstranit</a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            <?php endif ?>
        </tr>
    <?php endforeach ?>
    </table>
<?php else : ?>
    <p>Zatím nejsou v databázi žádní pojištěnci.</p>
<?php endif ?>
