<div class="container">
    <h1 class="text-center">Profil pojištěnce</h1></br>
    <div class="row">
<div class="col-sm-4 col-md-4 col-lg-3">
    <img src="obrazky/profil_pojistence.png" alt="profilovy" style="max-width: 100%; height: auto;"/>
</div>
        <div class="col-12 col-md-8 col-lg-9">
            <h2><?= $jmeno . " " . $prijmeni ?></h2>
            <h6><?= "Datum narození: " . date('d.m.Y', strtotime($datumNarozeni)) . ", " . $vek . " let" ?></h6>
            <div class="row">
                <div class="col-md-6">
                    <h5>Kontaktní informace</h5>
                    <p>Email: <?= $email ?></p>
                    <p>Telefonní číslo: <?= $telefon ?></p>
                </div>
                <div class="col-md-6">
                    <h5>Adresa</h5>
                    <p><?= $adresa ?></p>
                    <p><?= $mesto ?></p>
                    <p><?= $psc ?></p>
                </div>
            </div>
            <?php if ($admin) : ?>
                <div class="row">
                    <div class="col-md-12 my-3">
                        <div class="d-flex justify-content-start">
                            <a class="btn tlacitko-warning me-2" href="editor/<?= $pojistenec['url'] ?>">Editovat</a>
                            <button type="button" class="btn tlacitko-danger" data-bs-toggle="modal" data-bs-target="#odstran">Odstranit</button>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="odstran">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Potvrzení odstranění</h4>
                            </div>
                            <div class="modal-body text-center">
                                Opravdu si přejete odstranit pojištěnce <?= $jmeno . " " . $prijmeni ?>?
                            </div>
                            <div class="modal-footer justify-content-center">
                                <button type="button" class="btn tlacitko-success" data-bs-dismiss="modal" >
                                    Vrátit
                                </button>
                                <button type="button" class="btn tlacitko-danger" data-bs-dismiss="modal" >
                                    <a href="pojistenec/<?= $pojistenec['url'] ?>/odstranit" style="color: white; text-decoration: none;">Odstranit</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
    <ul class="nav nav-tabs" id="pojistenecTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pojistenecPojisteniTab" data-bs-toggle="tab" role="tab" href="#pojisteni">Pojištění</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pojistenecUdalostiTab" data-bs-toggle="tab" role="tab" href="#udalosti">Pojistné události</a>
        </li>
    </ul>
    <div class="tab-content" id="tabContent">
        <div id="pojisteni" class="container tab-pane" role="tabpanel" fade"><?php include('tabPojisteni.phtml') ?></div>
        <div id="udalosti" class="container tab-pane" role="tabpanel" fade"><?php include('tabUdalosti.phtml') ?></div>
    </div>
</div>
<script>
    // Po načtení stránky aktivuje první záložku (pojisteni)
    window.addEventListener('DOMContentLoaded', (event) => {
        // Přidáme atributy 'aria-selected' a 'active' první záložce
        document.getElementById('pojistenecPojisteniTab').setAttribute('aria-selected', 'true');
        document.getElementById('pojisteni').classList.add('active');
    });
</script>