<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/pojisteni.localhost" />
        <meta charset="UTF-8" />
        <title><?= $titulek ?></title>
        <meta name="viewport" content="width=device-width, viewport-fit=cover"/>
        <meta name="description" content="<?= $popis ?>" />
        <meta name="keywords" content="<?= $klicovaSlova ?>" />
        <meta name="author" content="Gábi Dvorníková" />
        <link rel="shortcut icon" href="obrazky/ikona.ico" />
        <script src="../bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="../bootstrap.min.css"/>
        <link rel="stylesheet" href="../style.css" type="text/css"/>
    </head>
    <body class="d-flex flex-column min-vh-100">
        <div class="custom-cursor"></div>
        <header>
            <div>
                <?php foreach ($zpravy as $zprava) : ?>
                    <?php foreach ($zprava as $klic => $text) : ?>
                        <p class="zprava-<?= $klic ?>"><?= $text ?></p>
                    <?php endforeach ?>
                <?php endforeach ?>
            </div>
            <nav class="navbar navbar-expand-md border-bottom container-fluid">
                <div>
                    <a class="navbar-brand" href="uvod">
                        <div class="d-flex align-items-center">
                            <img src="obrazky/logo.png" class="d-inline-block align-top float-start" width="80" height="80" alt="Logo" />
                            <div class="ms-3">
                                <h1 class="m-0">Pojišťovna</h1>
                                <small class="m-0">pro kouzelné bytosti</small>
                            </div>
                        </div>
                    </a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#obsah-navigacni-listy" aria-controls="obsah-navigacni-listy" aria-expanded="false" aria-label="Rozbalit navigaci">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="container">
                    <div class="collapse navbar-collapse" id="obsah-navigacni-listy">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item">
                                <a class="nav-link" href="uvod">
                                    <button type="button" class="btn tlacitko-navigace">
                                        Homepage
                                    </button>
                                </a>
                            </li>
                            <?php if ($uzivatel) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="pojistenci">
                                        <button type="button" class="btn tlacitko-navigace">
                                            Pojištenci
                                        </button>
                                    </a>
                                </li>
                            <?php endif ?>
                            <li class="nav-item">
                                <a class="nav-link" href="pojisteni">
                                    <button type="button" class="btn tlacitko-navigace">
                                        Pojištění
                                    </button>
                                </a>
                            </li>
                            <?php if (!$uzivatel) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="kontakt">
                                        <button type="button" class="btn tlacitko-navigace">
                                            Kontakt
                                        </button>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="faq">
                                        <button type="button" class="btn tlacitko-navigace">
                                            FAQ
                                        </button>
                                    </a>
                                </li>
                            <?php endif ?>
                        </ul>
                        <ul class="navbar-nav">
                            <?php if (!$uzivatel) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="prihlaseni">
                                        <button type="button" class="btn tlacitko-warning">
                                            Přihlásit
                                        </button>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="registrace">
                                        <button type="button" class="btn tlacitko-success">
                                            Registrovat
                                        </button>
                                    </a>
                                </li>
                            <?php endif ?>
                            <?php if ($uzivatel) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="profil">
                                        <button type="button" class="btn tlacitko-warning">
                                            Profil
                                        </button>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <div class="nav-link">
                                        <button type="button" class="btn tlacitko-danger" data-bs-toggle="modal" data-bs-target="#odhlas">
                                            Odhlásit
                                        </button>
                                    </div>
                                </li>
                            </ul>
                            <div class="modal" id="odhlas">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Potvrzení odhlášení</h4>
                                        </div>
                                        <div class="modal-body text-center">
                                            Opravdu se chcete odhlásit?
                                        </div>
                                        <div class="modal-footer justify-content-center">
                                            <button type="button" class="btn btn-success" data-bs-dismiss="modal">
                                                Vrátit
                                            </button>
                                            <a href="profil/odhlasit" class="btn btn-danger" role="button">Odhlásit</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                </div>
            </nav>
            <br clear = "both" />
        </header>
        <div class="container mx-auto flex-grow-1">
            <article>
                <?php $this->kontroler->vypisPohled();
                ?>
            </article>
        </div>
        <footer class="text-center mt-5 border-top">
            <p>&copy; <?php echo($rok) ?> Pojištění pro kouzelné bytosti</p>
        </footer>
        <script src="../script.js" defer></script>
    </body>
</html>
