<div class="d-flex justify-content-center mt-3">
    <button type="button" class="btn tlacitko-success" data-bs-toggle="modal" data-bs-target="#nove_pojisteni">Přidat nové pojištění</button>
</div>
<div class="modal" id="nove_pojisteni">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Nové pojištění pro pojištěnce <?= $jmeno . " " . $prijmeni ?></h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form method="post" class="needs-validation" novalidate id="novePojisteniFormular">
                <div class="modal-body">
                    <div class="container">
                        <input type="hidden" name="pojistenec_id" value="<?= $pojistenec['pojistenci_id'] ?>" />
                        <div>
                            <h6 class="mt-3"><label for="typ_pojisteni" class="form-label">Typ pojištění</label></h6>
                            <select class="form-select" id="typ_pojisteni" name="typ_pojisteni" required>
                                <option value="Úrazové">Úrazové</option>
                                <option value="Důchodové">Důchodové</option>
                                <option value="Nemocenské">Nemocenské</option>
                                <option value="Cestovní">Cestovní</option>
                                <option value="Havarijní">Havarijní</option>
                            </select>
                        </div>
                        <div>
                            <h6 class="mt-3"><label for="predmet_pojisteni" class="form-label">Předmět pojištění</label></h6>
                            <select class="form-select" id="predmet_pojisteni" name="predmet_pojisteni" required>
                                <option value="Pojištěnec"><?= $jmeno . " " . $prijmeni ?></option>
                                <option value="Příbuzný">Příbuzný klienta</option>
                                <option value="Vozidlo">Vozidlo</option>
                                <option value="Nemovitost">Nemovitost</option>
                            </select>
                        </div>
                        <div>
                            <h6 class="mt-3">Platnost</h6>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="od" class="form-label">Od:</label>
                                    <input type="date" name="od" class="form-control" id="od" value="<?php echo date('Y-m-d') ?>" min="<?= date('Y-m-d') ?>" required/>
                                    <div class="invalid-feedback" id="od_feedback"></div>
                                </div>
                                <div class="col-md-6">
                                    <label for="do" class="form-label">Do:</label>
                                    <input type="date" name="do" class="form-control" id="do" min="<?= date('Y-m-d') ?>" data-bs-toggle="tooltip" data-html="true" title="Uveďte, pokud je stanoveno datum ukončení"/>
                                    <div class="invalid-feedback" id="do_feedback"></div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <h6 class="mt-3"><label for="castka" class="form-label">Platba</label></h6>
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="number" name="castka" id="castka" class="form-control" oninput="validovatCislo(this)" value="10" min="10" required/>
                                    <div class="invalid-feedback">Hodnota musí být minimálně 10 korun</div>
                                </div>
                                <div class="col-md-6">
                                    <select class="form-select" name="frekvence_platby" id="frekvence_platby" required>
                                        <option value="Jednorázově">Jednorázově</option>
                                        <option value="Měsíčně">Měsíčně</option>
                                        <option value="Čtvrtletně">Čtvrtletně</option>
                                        <option value="Ročně">Ročně</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="submit" class="btn tlacitko-success" id="tlacitkoPridatPojisteni">Přidat pojištění</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <?php if ($pojisteniPojistence) : ?>
        <table class="table table-striped table-bordered table-hover my-3">
            <thead>
            <th>Typ pojištění</th>
            <th>Předmět</th>
            <th>Platnost</th>
            <th>Částka</th>
            <th>Platba</th>
            <th>Zaplaceno</th>
            <th>Úpravy</th>
            </thead>
            <?php foreach ($pojisteniPojistence as $pojisteniPojistence) : ?>   
                <tr> 
                <div>
                    <td><?= $pojisteniPojistence['typ_pojisteni'] ?></td>
                    <td>
                        <?php if ($pojisteniPojistence['predmet_pojisteni'] === 'Pojištěnec') : ?>
                            <?= $pojistenec['jmeno'] . " " . $pojistenec['prijmeni'] ?>
                        <?php else : ?>
                            <?= $pojisteniPojistence['predmet_pojisteni'] ?>
                        <?php endif ?>
                    </td>
                    <td>
                        <?php if ($pojisteniPojistence['do'] === '0000-00-00' || $pojisteniPojistence['do'] === '0' || $pojisteniPojistence['do'] === null) : ?>
                            <?= date('d.m.Y', strtotime($pojisteniPojistence['od'])) . " - bez ukončení" ?>
                        <?php endif ?>
                        <?php if ($pojisteniPojistence['do'] != '0000-00-00' && $pojisteniPojistence['do'] != '0' && $pojisteniPojistence['do'] != null) : ?>
                            <?= date('d.m.Y', strtotime($pojisteniPojistence['od'])) . " - " . date('d.m.Y', strtotime($pojisteniPojistence['do'])) ?>
                        <?php endif ?>
                    </td>
                    <td><?= $pojisteniPojistence['castka'] ?></td>
                    <td><?= $pojisteniPojistence['frekvence_platby'] ?></td>
                    <td><?= $pojisteniPojistence['celkem_zaplaceno'] ?></td>
                </div>
                        <td>
                            <div class="container m-md-1 d-flex">
                                    <button type="button" class="btn btn-sm tlacitko-warning" data-bs-toggle="modal" data-bs-target="#uprav-<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                        Editovat
                                    </button>
                                <div class="modal" id="uprav-<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Upravte <?= mb_strtolower($pojisteniPojistence['typ_pojisteni']) ?> pojištění pojištěnce <?= $jmeno . " " . $prijmeni ?></h4>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                            </div>
                                            <form method="post" class="needs-validation" novalidate id="editacePojisteniFormular">
                                                <div class="modal-body">
                                                    <div class="container">
                                                        <input type="hidden" name="pojisteni_id" id="pojisteni_id_editace" value="<?= $pojisteniPojistence['pojisteni_id'] ?>" />
                                                        <div>
                                                            <h6 class="mt-3"><label for="typ_pojisteni" class="form-label">Typ pojištění</label></h6>
                                                            <input type="text" class="form-control" id="typ_pojisteni_editace" name="typ_pojisteni" value="<?= $pojisteniPojistence['typ_pojisteni'] ?>" disabled="disabled"/>
                                                        </div>
                                                        <div>
                                                            <h6 class="mt-3"><label for="predmet_pojisteni" class="form-label">Předmět pojištění</label></h6>
                                                            <?php if ($pojisteniPojistence['predmet_pojisteni'] === 'Pojištěnec') : ?>
                                                                <input type="text" class="form-control" id="predmet_pojisteni_editace" name="predmet_pojisteni" value="<?= $pojistenec['jmeno'] . " " . $pojistenec['prijmeni'] ?>" disabled="disabled"/>
                                                            <?php else : ?>
                                                                <input type="text" class="form-control" id="predmet_pojisteni_editace" name="predmet_pojisteni" value="<?= $pojisteniPojistence['typ_pojisteni'] ?>" disabled="disabled"/>
                                                            <?php endif ?>
                                                        </div>
                                                        <div>
                                                            <h6 class="mt-3">Platnost</h6>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label for="od" class="form-label">Od:</label>
                                                                    <input type="date" name="od" class="form-control" id="od_editace" value="<?= $pojisteniPojistence['od'] ?>" disabled="disabled"/>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <label for="do" class="form-label">Do:</label>
                                                                    <input type="date" name="do" class="form-control" id="do_editace" value="<?= $pojisteniPojistence['do'] ?>" min="<?= date('Y-m-d') ?>" data-bs-toggle="tooltip" data-html="true" title="Uveďte, pokud je stanoveno datum ukončení"/>
                                                                    <div class="invalid-feedback" id="do_editace_feedback"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div>
                                                            <h6 class="mt-3"><label for="castka" class="form-label">Platba</label></h6>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <input type="number" name="castka" class="form-control" id="castka_editace" oninput="validovatCislo(this)" value="<?= $pojisteniPojistence['castka'] ?>" min="10" required/>
                                                                    <div class="invalid-feedback">Hodnota musí být minimálně 10 korun</div>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <select class="form-select" id="frekvence_platby_editace" name="frekvence_platby" required>
                                                                        <option value="Měsíčně">Měsíčně</option>
                                                                        <option value="Čtvrtletně">Čtvrtletně</option>
                                                                        <option value="Ročně">Ročně</option>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer justify-content-center">
                                                    <button type="submit" class="btn tlacitko-success" id="tlacitkoUpravitPojisteni"">Upravit pojištění</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <button type="button" class="btn btn-sm tlacitko-danger" data-bs-toggle="modal" data-bs-target="#odstran-<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                    Odstranit
                                </button>
                                <div class="modal" id="odstran-<?= $pojisteniPojistence['pojisteni_id'] ?>">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Potvrzení odstranění</h4>
                                            </div>
                                            <div class="modal-body text-center">
                                                Opravdu si přejete odstranit <?= mb_strtolower($pojisteniPojistence['typ_pojisteni']) ?> pojištění?
                                            </div>
                                            <form method="post">
                                                <input type="hidden" name="pojisteni_id" value="<?= $pojisteniPojistence['pojisteni_id'] ?>" />
                                                <input type="hidden" name="odstranit" value="odstranit" />
                                                <div class="modal-footer justify-content-center">
                                                    <button type="button" class="btn tlacitko-success" data-bs-dismiss="modal" >
                                                        Vrátit
                                                    </button>
                                                    <button type="submit" class="btn tlacitko-danger" data-bs-dismiss="modal" >
                                                        Odstranit
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                </tr>
            <?php endforeach ?>
        </table>
    <?php endif ?>
</div>

<script>
    // Formulářová validace při vytváření pojištění
    var novePojisteniFormular = document.getElementById('novePojisteniFormular');
    var tlacitkoPridatPojisteni = document.getElementById('tlacitkoPridatPojisteni');

    novePojisteniFormular.addEventListener('submit', function (event) {
        if (!novePojisteniFormular.checkValidity()) {
            event.preventDefault();
            event.stopPropagation();
        }

        novePojisteniFormular.classList.add('was-validated');
    });

    document.addEventListener('DOMContentLoaded', function () {
        var typPojisteniSelect = document.getElementById('typ_pojisteni');
        var predmetPojisteniSelect = document.getElementById('predmet_pojisteni');
        var frekvencePlatbySelect = document.getElementById('frekvence_platby');

        typPojisteniSelect.addEventListener('change', function () {
            var selectedValue = typPojisteniSelect.value;

            if (selectedValue === 'Cestovní') {
                frekvencePlatbySelect.innerHTML = '';

                var option1 = document.createElement('option');
                option1.value = 'Jednorázově';
                option1.text = 'Jednorázově';
                frekvencePlatbySelect.add(option1);

                var option2 = document.createElement('option');
                option2.value = 'Měsíčně';
                option2.text = 'Měsíčně';
                frekvencePlatbySelect.add(option2);

                var option3 = document.createElement('option');
                option3.value = 'Čtvrtletně';
                option3.text = 'Čtvrtletně';
                frekvencePlatbySelect.add(option3);

                var option4 = document.createElement('option');
                option4.value = 'Ročně';
                option4.text = 'Ročně';
                frekvencePlatbySelect.add(option4);
            } else {
                frekvencePlatbySelect.innerHTML = '';

                var option1 = document.createElement('option');
                option1.value = 'Měsíčně';
                option1.text = 'Měsíčně';
                frekvencePlatbySelect.add(option1);

                var option2 = document.createElement('option');
                option2.value = 'Čtvrtletně';
                option2.text = 'Čtvrtletně';
                frekvencePlatbySelect.add(option2);

                var option3 = document.createElement('option');
                option3.value = 'Ročně';
                option3.text = 'Ročně';
                frekvencePlatbySelect.add(option3);
            }

            if (selectedValue === 'Cestovní' || selectedValue === 'Úrazové' || selectedValue === 'Nemocenské') {
                predmetPojisteniSelect.innerHTML = '';
                var option1 = document.createElement('option');
                option1.value = 'Pojištěnec';
                option1.text = 'Pojištěnec';
                predmetPojisteniSelect.add(option1);

                var option2 = document.createElement('option');
                option2.value = 'Příbuzný klienta';
                option2.text = 'Příbuzný klienta';
                predmetPojisteniSelect.add(option2);
            } else if (selectedValue === 'Důchodové') {
                predmetPojisteniSelect.innerHTML = '';
                var option1 = document.createElement('option');
                option1.value = 'Pojištěnec';
                option1.text = 'Pojištěnec';
                predmetPojisteniSelect.add(option1);
            } else if (selectedValue === 'Havarijní') {
                predmetPojisteniSelect.innerHTML = '';
                var option1 = document.createElement('option');
                option1.value = 'Vozidlo';
                option1.text = 'Vozidlo';
                predmetPojisteniSelect.add(option1);

                var option2 = document.createElement('option');
                option2.value = 'Nemovitost';
                option2.text = 'Nemovitost';
                predmetPojisteniSelect.add(option2);
            }
        });
        typPojisteniSelect.dispatchEvent(new Event('change'));
    });

document.getElementById('od').addEventListener('change', function () {
    var odValue = new Date(document.getElementById('od').value);
    var doValue = new Date(document.getElementById('do').value);

    if (odValue > doValue) {
        document.getElementById('od_feedback').innerText = 'Začátek platnosti nemůže nastat po konci platnosti';
    } else {
        document.getElementById('od_feedback').innerText = ''; // Vymazat chybovou zprávu, pokud je validace úspěšná
    }
});

document.getElementById('do').addEventListener('change', function () {
    var odValue = new Date(document.getElementById('od').value);
    var doValue = new Date(document.getElementById('do').value);

    if (odValue > doValue) {
        document.getElementById('od_feedback').innerText = 'Začátek platnosti nemůže nastat po konci platnosti';
    } else {
        document.getElementById('od_feedback').innerText = ''; // Vymazat chybovou zprávu, pokud je validace úspěšná
    }
});

    // Formulářová validace pro datum začátku platnosti
    document.getElementById('od').addEventListener('change', function () {
        var inputDate = new Date(this.value);
        var today = new Date();
        var odValue = new Date(document.getElementById('od').value);
        var doValue = new Date(document.getElementById('do').value);

        if (inputDate < today) {
            document.getElementById('od_feedback').innerText = 'Začátek platnosti nelze nastavovat zpětně';
        } else if (odValue > doValue) {
            document.getElementById('od_feedback').innerText = 'Začátek platnosti nemůže nastat po konci platnosti';
        } else {
            document.getElementById('od_feedback').innerText = 'Vyplňte celé datum';
        }
    });

// Formulářová validace pro datum ukončení platnosti při vytváření pojištění
    document.getElementById('do').addEventListener('change', function () {
        var inputDate = new Date(this.value);
        var today = new Date();

        if (inputDate < today) {
            document.getElementById('do_feedback').innerText = 'Konec platnosti nemůže být v minulosti';
        } else {
            document.getElementById('do_feedback').innerText = 'Vyplňte celé nebo žádné datum';
        }

    });

    // Formulářová validace při editaci pojištění
    var editacePojisteniFormular = document.getElementById('editacePojisteniFormular');
    var tlacitkoUpravitPojisteni = document.getElementById('tlacitkoUpravitPojisteni');

    editacePojisteniFormular.addEventListener('submit', function (event) {
        if (!editacePojisteniFormular.checkValidity()) {
            event.preventDefault();
            event.stopPropagation();
        }

        editacePojisteniFormular.classList.add('was-validated');
    });

    // Formulářová validace pro datum ukončení platnosti při editaci pojištění
    document.getElementById('do_editace').addEventListener('change', function () {
        var inputDate = new Date(this.value);
        var today = new Date();

        if (inputDate < today) {
            document.getElementById('do_editace_feedback').innerText = 'Konec platnosti nelze nastavovat zpětně';
        } else {
            document.getElementById('do_editace_feedback').innerText = 'Vyplňte celé nebo žádné datum';
        }
    });

    // Funkce pro validaci čísel a délky
    function validovatCislo(input) {
        // Odstranit všechny nečíselné znaky
        input.value = input.value.replace(/\D/g, '');
        // Omezit délku na 7 znaků
        if (input.value.length > 7) {
            input.value = input.value.slice(0, 7);
        }
    }
</script>
